# Generated by Django 5.2.7 on 2025-10-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
        ('pizza_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_shops.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
