# Generated by Django 5.2.7 on 2025-10-28 18:43

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
