# Generated by Django 5.2.7 on 2025-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ingredients', models.JSONField(default=list)),
                ('time_prepared', models.DateTimeField()),
            ],
            options={
                'db_table': 'Pizzas',
            },
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
