# Generated by Django 5.2.7 on 2025-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzamodel_delete_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'managed': True},
        ),
    ]
