# Generated by Django 5.2.7 on 2025-10-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={},
        ),
    ]
