# Generated by Django 5.2.7 on 2025-10-27 18:38

from django.db import migrations

import apps.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
    ]
